version: '3.8'

services:
  mariadb:
    build: .
    container_name: mariadb-springboot
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springboot
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - tp-complet

    restart: unless-stopped

volumes:
  mariadb_data:

networks:
  tp-complet:
    driver: bridge
    name: tp-complet