version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-tp
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - tp-complet
    restart: unless-stopped

volumes:
  grafana_data:

networks:
  tp-complet:
    driver: bridge
    name: tp-complet